# Generated by Django 2.2.24 on 2021-09-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0004_chamado'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='proprietario_apelido',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='proprietario_nome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
