# Generated by Django 2.2.24 on 2021-09-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0006_equipment_qtchamados'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='qtequipments',
            field=models.IntegerField(null=True),
        ),
    ]
